### ISSUE TITLE
TypeError: Secret string must be provided.

### ISSUE THREAD

**Issue by LeighPlays** [ShpeeBot/ShpeeBot#2]
When Am Going To Sign In With Discord! And That's Show In My Command Line!
Please Help
Please Respond :(

**Comment by LeoDoesThings** [comment]
Sorry about that, this will be fixed in a later release.
**You can solve this pretty quickly by changing your session secret in your config file.**

The default is: 
```js
sessionSecret: Math.random(),
```
Please change the `Math.random()` to a long passphrase or just a random set of letters and symbols.

Examples:
```js
sessionSecret: "lksmpoirthufglkr!#51%[;')8",
```
```js
sessionSecret: "discord_is_110%_AWESOME",
```

**Comment by LeighPlays** [comment]
i do that and now this is show

Error: /app/dashboard/templates/dashboard.ejs:14
    12|       <nav class="navbar navbar-dark navbar-expand sticky-top">
    13|         <p class="navbar-brand h4">Dashboard</p>
 >> 14|                 <%- include('blocks/navbar') %>
    15|       </nav>
    16| 
    17|       <h1 class="display-3">Dashboard</h1>

Could not find the include file "blocks/navbar"
    at getIncludePath (/rbd/pnpm-volume/4851d0ec-9cd5-4ca1-9811-8fe171446669/node_modules/.registry.npmjs.org/ejs/3.1.5/node_modules/ejs/lib/ejs.js:183:13)
    at includeFile (/rbd/pnpm-volume/4851d0ec-9cd5-4ca1-9811-8fe171446669/node_modules/.registry.npmjs.org/ejs/3.1.5/node_modules/ejs/lib/ejs.js:309:19)
    at include (/rbd/pnpm-volume/4851d0ec-9cd5-4ca1-9811-8fe171446669/node_modules/.registry.npmjs.org/ejs/3.1.5/node_modules/ejs/lib/ejs.js:689:16)
    at eval (/app/dashboard/templates/dashboard.ejs:15:17)
    at dashboard (/rbd/pnpm-volume/4851d0ec-9cd5-4ca1-9811-8fe171446669/node_modules/.registry.npmjs.org/ejs/3.1.5/node_modules/ejs/lib/ejs.js:691:17)
    at tryHandleCache (/rbd/pnpm-volume/4851d0ec-9cd5-4ca1-9811-8fe171446669/node_modules/.registry.npmjs.org/ejs/3.1.5/node_modules/ejs/lib/ejs.js:272:36)
    at View.exports.renderFile [as engine] (/rbd/pnpm-volume/4851d0ec-9cd5-4ca1-9811-8fe171446669/node_modules/.registry.npmjs.org/ejs/3.1.5/node_modules/ejs/lib/ejs.js:489:10)
    at View.render (/rbd/pnpm-volume/4851d0ec-9cd5-4ca1-9811-8fe171446669/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/view.js:135:8)
    at tryRender (/rbd/pnpm-volume/4851d0ec-9cd5-4ca1-9811-8fe171446669/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/application.js:640:10)
    at Function.render (/rbd/pnpm-volume/4851d0ec-9cd5-4ca1-9811-8fe171446669/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/application.js:592:3)

**Comment by LeighPlays** [comment]
Error: /app/dashboard/templates/dashboard.ejs:14
    12|       <nav class="navbar navbar-dark navbar-expand sticky-top">
    13|         <p class="navbar-brand h4">Dashboard</p>
 >> 14|                 <%- include('blocks/navbar') %>
    15|       </nav>
    16| 
    17|       <h1 class="display-3">Dashboard</h1>

Could not find the include file "blocks/navbar"
    at getIncludePath (/rbd/pnpm-volume/4851d0ec-9cd5-4ca1-9811-8fe171446669/node_modules/.registry.npmjs.org/ejs/3.1.5/node_modules/ejs/lib/ejs.js:183:13)
    at includeFile (/rbd/pnpm-volume/4851d0ec-9cd5-4ca1-9811-8fe171446669/node_modules/.registry.npmjs.org/ejs/3.1.5/node_modules/ejs/lib/ejs.js:309:19)
    at include (/rbd/pnpm-volume/4851d0ec-9cd5-4ca1-9811-8fe171446669/node_modules/.registry.npmjs.org/ejs/3.1.5/node_modules/ejs/lib/ejs.js:689:16)
    at eval (/app/dashboard/templates/dashboard.ejs:15:17)
    at dashboard (/rbd/pnpm-volume/4851d0ec-9cd5-4ca1-9811-8fe171446669/node_modules/.registry.npmjs.org/ejs/3.1.5/node_modules/ejs/lib/ejs.js:691:17)
    at tryHandleCache (/rbd/pnpm-volume/4851d0ec-9cd5-4ca1-9811-8fe171446669/node_modules/.registry.npmjs.org/ejs/3.1.5/node_modules/ejs/lib/ejs.js:272:36)
    at View.exports.renderFile [as engine] (/rbd/pnpm-volume/4851d0ec-9cd5-4ca1-9811-8fe171446669/node_modules/.registry.npmjs.org/ejs/3.1.5/node_modules/ejs/lib/ejs.js:489:10)
    at View.render (/rbd/pnpm-volume/4851d0ec-9cd5-4ca1-9811-8fe171446669/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/view.js:135:8)
    at tryRender (/rbd/pnpm-volume/4851d0ec-9cd5-4ca1-9811-8fe171446669/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/application.js:640:10)
    at Function.render (/rbd/pnpm-volume/4851d0ec-9cd5-4ca1-9811-8fe171446669/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/application.js:592:3)

**Comment by LeighPlays** [comment]
help

**Comment by LeighPlays** [comment]
when i open dashboard

**Comment by LeoDoesThings** [comment]
**Thanks for reporting that.
I will also fix that in the next release.**

It also sounds like you are going to use ShpeeBot in production instead of just testing.
Right now ShpeeBot is in alpha so there will be many issues. There are plenty other Discord bots available on GitHub that you can use in the meantime.

**Comment by LeighPlays** [comment]
Oh ok!  I credit you :)
