### ISSUE TITLE
Dashboard isnt working

### ISSUE THREAD

**Issue by xX-Joni-Xx** [ShpeeBot/ShpeeBot#3]
I got this error:

TypeError: Secret string must be provided.
    at Object.exports.unsign (/home/pi/ShpeeBot/node_modules/cookie-signature/index.js:38:40)
    at unsigncookie (/home/pi/ShpeeBot/node_modules/express-session/index.js:677:28)
    at getcookie (/home/pi/ShpeeBot/node_modules/express-session/index.js:542:15)
    at session (/home/pi/ShpeeBot/node_modules/express-session/index.js:217:36)
    at Layer.handle [as handle_request] (/home/pi/ShpeeBot/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/pi/ShpeeBot/node_modules/express/lib/router/index.js:317:13)
    at /home/pi/ShpeeBot/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/pi/ShpeeBot/node_modules/express/lib/router/index.js:335:12)
    at next (/home/pi/ShpeeBot/node_modules/express/lib/router/index.js:275:10)
    at logger (/home/pi/ShpeeBot/node_modules/morgan/index.js:144:5)

**Comment by LeoDoesThings** [comment]
Was explained in #2 here: https://github.com/ShpeeBot/ShpeeBot/issues/2#issuecomment-761536194

I'm not really working on this project anymore so it's probably best you find another bot to use.

**Comment by xX-Joni-Xx** [comment]
Do you know a advanced bot with many features and a nice dashboard?

**Comment by xX-Joni-Xx** [comment]
Ok the Homepage is working but afer the log-in i got this error:

Error: /home/pi/ShpeeBot/dashboard/templates/dashboard.ejs:14
    12|       <nav class="navbar navbar-dark navbar-expand sticky-top">
    13|         <p class="navbar-brand h4">Dashboard</p>
 >> 14|         <%- include('blocks/navbar') %>
    15|       </nav>
    16| 
    17|       <h1 class="display-3">Dashboard</h1>

Could not find the include file "blocks/navbar"
    at getIncludePath (/home/pi/ShpeeBot/node_modules/ejs/lib/ejs.js:183:13)
    at includeFile (/home/pi/ShpeeBot/node_modules/ejs/lib/ejs.js:309:19)
    at include (/home/pi/ShpeeBot/node_modules/ejs/lib/ejs.js:690:16)
    at eval (eval at compile (/home/pi/ShpeeBot/node_modules/ejs/lib/ejs.js:662:12), <anonymous>:15:17)
    at dashboard (/home/pi/ShpeeBot/node_modules/ejs/lib/ejs.js:692:17)
    at tryHandleCache (/home/pi/ShpeeBot/node_modules/ejs/lib/ejs.js:272:36)
    at View.exports.renderFile [as engine] (/home/pi/ShpeeBot/node_modules/ejs/lib/ejs.js:489:10)
    at View.render (/home/pi/ShpeeBot/node_modules/express/lib/view.js:135:8)
    at tryRender (/home/pi/ShpeeBot/node_modules/express/lib/application.js:640:10)
    at Function.render (/home/pi/ShpeeBot/node_modules/express/lib/application.js:592:3)

**Comment by LeoDoesThings** [comment]
You can change `blocks/navbar` to `blocks/header`. 
Any other issues that come up will probably need proper digging around in the code.
