### ISSUE TITLE
I have an Issues with the Dashboard

### ISSUE THREAD

**Issue by xX-Joni-Xx** [ShpeeBot/ShpeeBot#4]
I tried `blocks/navbar` and `blocks/header`

Error:
```
TypeError: /home/pi/ShpeeBot/dashboard/templates/dashboard.ejs:14
    12|       <nav class="navbar navbar-dark navbar-expand sticky-top">
    13|         <p class="navbar-brand h4">Dashboard</p>
 >> 14|         <%- include('blocks/header') %>
    15|       </nav>
    16| 
    17|       <h1 class="display-3">Dashboard</h1>

/home/pi/ShpeeBot/dashboard/templates/blocks/header.ejs:33
    31|       <img
    32|         class="rounded-circle"
 >> 33|         src="<%= user.avatarURL({ format: 'png', dynamic: true, size: 35 }) %>"
    34|         width="35"
    35|         height="35"
    36|         style="margin-bottom: 4px; margin-right: 2px;"

user.avatarURL is not a function
    at eval (eval at compile (/home/pi/ShpeeBot/node_modules/ejs/lib/ejs.js:662:12), <anonymous>:15:31)
    at header (/home/pi/ShpeeBot/node_modules/ejs/lib/ejs.js:692:17)
    at include (/home/pi/ShpeeBot/node_modules/ejs/lib/ejs.js:690:39)
    at eval (eval at compile (/home/pi/ShpeeBot/node_modules/ejs/lib/ejs.js:662:12), <anonymous>:15:17)
    at dashboard (/home/pi/ShpeeBot/node_modules/ejs/lib/ejs.js:692:17)
    at tryHandleCache (/home/pi/ShpeeBot/node_modules/ejs/lib/ejs.js:272:36)
    at View.exports.renderFile [as engine] (/home/pi/ShpeeBot/node_modules/ejs/lib/ejs.js:489:10)
    at View.render (/home/pi/ShpeeBot/node_modules/express/lib/view.js:135:8)
    at tryRender (/home/pi/ShpeeBot/node_modules/express/lib/application.js:640:10)
    at Function.render (/home/pi/ShpeeBot/node_modules/express/lib/application.js:592:3)

**Comment by LeoDoesThings** [comment]
#3 
> Any other issues that come up will probably need proper digging around in the code.

I am currently not maintaining this project anymore.
I haven't archived yet because I plan on finishing this at some point but I'm not going to be providing support for an issue that needs proper changes in code.

You can find another discord.js bot to use, there are literally thousands of them on GitHub.
Stop bothering me about an issue I have already said I won't fix.
